### ISSUE TITLE
Missing dependencies for Linux

### ISSUE THREAD

**Issue by MF366-Coding** [MF366-Coding/WriterClassic#18]
# How it happened?
I was testing WriterClassic on Linux and I clicked **About**.

But I just got a blank window with nothing inside of it.

# What is the problem?
The title already says it all: missing dependencies for Linux.

# How to fix it?
You can easily fix it by installing those dependencies.

WriterClassic uses 2 modules that don't come with Linux by default. `tkinter` and `PIL`.

Those modules must be installed with the package manager of your Linux distro, not with `pip`.

Their packages' names are:
```
python3-tk
python3-pil
python3-pil.imagetk
```

`python3-pil.imagetk` is used to place WriterClassic's logo on the **About** window.

It is separated from `python3-pil`, which means you'll have to install both to acess both `PIL` and PIL's `ImageTk`. Don't forget to install `tkinter` too!

**Comment by norbcodes** [comment]
Maybe difficult to implement, but maybe  have the packages be installed when you run the Installation Wizard?

**Comment by MF366-Coding** [comment]
The Installation Wizard is an executable so it wouldn't run on Linux without an emulation service.

**Comment by norbcodes** [comment]
Oh yea I forgot this is a Linux issue lol

Maybe make the python file itself somehow download the packages?

**Comment by MF366-Coding** [comment]
I am sure that would be possible by using `sys.platform == "linux"` and `os.system()`.

The problem is: how can I know what is the pckage manager of the Linux Distro the user is using? There isn't a unique package manager for all distros.

**Comment by norbcodes** [comment]
maybe look into this?

https://pypi.org/project/distro/
