### ISSUE TITLE
Add *.wclassic file variables

### ISSUE THREAD

**Issue by MF366-Coding** [MF366-Coding/WriterClassic#43]
# Description
My plan with this feature is making *.wclassic files more useful. Instead of just being alternatives to *.txt they are gonna be given more functionality: **system variables**.

# How it would work
When the user creates a *.wclassic file, he can place (doesn't matter where) this string: `$VARS`.

If, when saving or opening a file, WriterClassic finds this string, it will proceed to replace all the variables, that are also prefixed with `$`, by their values on the working device.

## Example
If we had the following file:
```
This is a test on $VARS inside WriterClassic. My appdata folder is at $APPDATA.
```

It would be transformed into this when saving:
```
This is a test on $VARS inside WriterClassic. My appdata folder is at C:\Users\john\AppData\
```

## Things worth mentioning
- The `$VARS` string stays there
- WriterClassic must have this variables stored as a `dict[str, str]` when the app launches
- This depends on the system. `$APPDATA` must be only replaced if the OS is Windows. However, `$HOMEDIR` could be OS Independent, refering to the directory of the user

**Comment by MF366-Coding** [comment]
# Something I forgot
I completely forgot to mention this: after the file is saved and the variables replaced, the file must be reloaded. That of course isn't hard:
```py
OpenFileManually(NOW_FILE) # after saving
```
This should work and Sorry, @norbcodes for getting in your way. 😅

**Comment by norbcodes** [comment]
👍

**Comment by MF366-Coding** [comment]
Some variables could be:
```
$APPDATA
$LOCAL_APPDATA
$PROGRAM_FILES
$REPO - the site of the WriterClassic repo
```

Just ideas though.
