### ISSUE TITLE
Implement Ctrl + A and Select All

### ISSUE THREAD

**Issue by MF366-Coding** [MF366-Coding/WriterClassic#46]
# Description
When the user presses **Ctrl + A**, all the text in the Text Widget will be selected.

**Comment by MF366-Coding** [comment]
@norbcodes Hey, dude. I know you want to do this but I might have found a solution. Could I work on it and then if it doens't work, you can try yourself?

**Comment by norbcodes** [comment]
Sure, go ahead @MF366-Coding

**Comment by MF366-Coding** [comment]
Thanks!

**Comment by MF366-Coding** [comment]
Done, will be released next version too.
