### ISSUE TITLE
Fix casual typing

### ISSUE THREAD

**Issue by MF366-Coding** [MF366-Coding/WriterClassic#70]
## Description
A setting that can be turned **ON** and **OFF**. When **ON**, when you save a document, casual expressions are replaced by more formal ones.

### Short Example
- `rn` gets replaced with `right now`

Also, `rN` gets replaced with `right Now` so it adjusts to the casing.

**Comment by norbcodes** [comment]
People that use "rn" instead of "right now" use the saved time to make software like this

**Comment by MF366-Coding** [comment]
LMFAO indeed my friend

**Comment by norbcodes** [comment]
❤

**Comment by MF366-Coding** [comment]
Will work on this tomorrow.
