### ISSUE TITLE
Plugin Central

### ISSUE THREAD

**Issue by MF366-Coding** [MF366-Coding/WriterClassic#87]
## Description
A feature rich **Plugin Central** that allows for installing, running and uninstalling plugins.

I guess that for further information on this I'll attach a sketch I proudly made in Paint for the Plugin Central.

**Comment by MF366-Coding** [comment]
## Concept
Please note that this is just a concept for the features and GUI, it might change and won't look exactly like this.

![Image](https://github.com/MF366-Coding/WriterClassic/assets/109810178/490f6a61-32a5-47a5-b24c-a805e453218e)

**Comment by norbcodes** [comment]
This sucks ass
(jk cool concept dude)

**Comment by MF366-Coding** [comment]
LMFAO, glad you like it dude

**Comment by MF366-Coding** [comment]
I'm gonna start working on this, I guess...

**Comment by norbcodes** [comment]
:)

**Comment by MF366-Coding** [comment]
**Development in this feature is on hold** as I am developing another project. **I will come back to the Plugin Central and WriterClassic in general ASAP.**

Thank you.

**Comment by MF366-Coding** [comment]
I'm back to WriterClassic, my main project, in order not to delay its v10.8.0 much longer.

**Comment by MF366-Coding** [comment]
This has been achieved.

**Comment by MF366-Coding** [comment]
Fun fact: this was started exactly 2 months ago according to the GitHub Projects start date.
